console.log(`
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEE,   EEEEEEEt jEEEEEEEEE; EEE   EEEEE   EEEEEEEEEE. EEEEL  EEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEE  EEEE  EEE  ;GE  ,EEEE  EE E EE, EE  EE  EEEEEEE  ,   EG EE     EE   tEEEEEEEEEEEEEEEEEEE
EEEEEEEEE  EEEEEE  E EEEEEEE. EEE EEE   EEE  E EEE; EEEEEEE ,j   L  E    E     E  EEEEEEEEEEEEEEEEEE
EEEEEEEEE EEE EEE   GEE..EEEEj E EEEE;  EEEE   EEE  EEEEEEE . E;   E t  EEE    E,  EEEEEEEEEEEEEEEEE
EEEEEEEE EEt   EE;  ,EE   GEE     EEEE   EEEE EEEE  EEEEEEEE EEE  E.;   EEE   EEE  .EEEEEEEEEEEEEEEE
EEEEEEEG EE    ,     EE;  EEEG   EE EE; . EEEEEEE   EEEEEEEEL GEE .G  , EEj  G. EE  EEEEEEEEEEEEEEEE
EEEEEEE EEE   .      EEEEEEEE   EjE EEL  . EEEEEt  EEEEEEEEEEE,EEEG   E EEE  E ;EE  EEEEEEEEEEEEEEEE
EEEEEEE GEE  EEE   t EEEEEEE.    E,EEEE  E. EEEj   EEEEEEEEEEt EEEE  EE EEE  E EEE  EEEEEEEEEEEEEEEE
EEEEEEE GEE  L  EE;   EEGEEEE  EEEGtEEE  E EEEEE  EEEEEEEEEEE EEEEEj EE GEEE  LEEE  EEEEEEEEEEEEEEEE
EEEEEEE ;GEE;EEEEE   EEE .EEEE  EE   EEL E EEEG. LEEEEEEEEE  E EtEEE   E EEEE EEEE  EEEEEEEEEEEEEEEE
EEEEEEEE EEEEEEE     EEEE tEEEL     E.EE   EEE.  EEEEEEEEE  E E   LEE  .E EEEEEEE;  EEEEEEEEEEEEEEEE
EEEEEEEE    ,      E EEE   EEE     EE ; j EEEG  GEEEEEEEEE jEE    E    EEE .EEEE,   EEEEEEEEEEEEEEEE
EEEEEEEEE;      EEEEE     E       ;EEE     Ett  EEEEEEEEEEG     EE.   tEEEEt       EEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEE   EEEG  tEEEEEEEEE tEL  EEEEEEEEEEEEE  ,EEEEE EEEEEEEEE G EEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEE EEEEEEEEEEE     EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEL   EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
`)